ifeq ($(strip $(GBDK_HOME)),)
$(error "Please set GBDK_HOME in your environment. export GBDK_HOME=<path to>GBDK_HOME")
endif

LCC = $(GBDK_HOME)/bin/lcc
PNG2ASSET = $(GBDK_HOME)/bin/png2asset

LCCFLAGS += -Wl-j -Wm-yc -Wm-ys # Game Boy & Game Boy Color & Super Game Boy
LCCFLAGS += -Wf-MMD -Wf-Wp-MP # Header file dependency output (-MMD) for Makefile use + per-header Phony rules (-MP)
CFLAGS += -Wf-MMD -Wf-Wp-MP # Header file dependency output (-MMD) for Makefile use + per-header Phony rules (-MP)

ifdef GBDK_DEBUG
	LCCFLAGS += -debug -v
endif

PROJECTNAME = FoxGirl
EXT 		= gb

SRCDIR      = src
OBJDIR      = obj
RESDIR      = res
BINDIR      = build
MKDIRS      = $(OBJDIR) $(BINDIR)
BINS	    = $(BINDIR)/$(PROJECTNAME).$(EXT)
RESOURCES   = $(foreach dir,$(RESDIR),$(notdir $(wildcard $(dir)/*.png)))
CSOURCES    = $(foreach dir,$(SRCDIR),$(notdir $(wildcard $(dir)/*.c))) $(foreach dir,$(RESDIR),$(notdir $(wildcard $(dir)/*.c)))
ASMSOURCES  = $(foreach dir,$(SRCDIR),$(notdir $(wildcard $(dir)/*.s)))
OBJS        = $(RESOURCES:%.png=$(OBJDIR)/%.o) $(CSOURCES:%.c=$(OBJDIR)/%.o) $(ASMSOURCES:%.s=$(OBJDIR)/%.o)

DEPS = $(OBJS:%.o=%.d)

all: $(BINS)

test:
	echo $(CSOURCES)

$(OBJDIR)/%.c:	$(RESDIR)/%.png
	$(eval FLAGS := $(shell grep "$$(basename $<)" $(RESDIR)/sprites_config.txt | cut -d':' -f2))
	$(PNG2ASSET) $< -c $@ $(FLAGS)

# Compile .c files in "src/" to .o object files
$(OBJDIR)/%.o:	$(SRCDIR)/%.c
	$(LCC) $(CFLAGS) -c -o $@ $<

# Compile .c files in "res/" to .o object files
$(OBJDIR)/%.o:	$(RESDIR)/%.c
	$(LCC) $(CFLAGS) -c -o $@ $<

# Compile .s assembly files in "src/" to .o object files
$(OBJDIR)/%.o:	$(SRCDIR)/%.s
	$(LCC) $(CFLAGS) -c -o $@ $<

# If needed, compile .c files in "src/" to .s assembly files
# (not required if .c is compiled directly to .o)
$(OBJDIR)/%.s:	$(SRCDIR)/%.c
	$(LCC) $(CFLAGS) -S -o $@ $<

# rule for the autogenerated files
$(OBJDIR)/%.o:	$(OBJDIR)/%.c
	$(LCC) $(LCCFLAGS) $(CFLAGS) -c -o $@ $<

# Link the compiled object files into a .gb ROM file
$(BINS):	$(OBJS)
	$(LCC) $(LCCFLAGS) $(CFLAGS) -o $(BINDIR)/$(PROJECTNAME).$(EXT) $(OBJS)

.PHONY: clean

clean:
	@echo clean ...
	@rm -fr $(OBJDIR) $(BINDIR)

ifneq ($(strip $(EXT)),)
$(info $(shell mkdir -p $(MKDIRS)))
endif

-include $(DEPS)